name: test
on: [push]

env:
  # tseval (via easse) has a dependency on the deprecated sklearn package
  # Statement below fixes a build error, but should be removed when below PR is merged
  # https://github.com/facebookresearch/text-simplification-evaluation/pull/3
  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2

      - name: Create conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: simple-patho

      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          micromamba activate simple-patho
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba activate simple-patho
          make test
          make lintci
